_LICENSE=LGPL21 MIT
_LICENSE_COMB=dual
_LICENSE_NAME=Dual (any of): LGPL21 MIT
_LICENSE_PERMS=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS=
_LICENSE_NAME_LGPL21 =GNU Lesser General Public License version 2.1
_LICENSE_PERMS_LGPL21 =dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_LGPL21 =FSF GPL OSI
_LICENSE_DISTFILES_LGPL21 =dovecot-2.2.33.2.tar.gz
_LICENSE_NAME_MIT =MIT license / X11 license
_LICENSE_PERMS_MIT =dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_MIT =COPYFREE FSF GPL OSI
_LICENSE_DISTFILES_MIT =dovecot-2.2.33.2.tar.gz
