# Created by: Vidar Karlsen <vidar@karlsen.tech>
# $FreeBSD$

PKGNAMESUFFIX+=	-python

MAINTAINER=	vidar@karlsen.tech
COMMENT=	Validating, recursive, and caching DNS resolver (python pkg)

OPTIONS_DEFAULT=PYTHON

MASTERDIR=	${.CURDIR}/../unbound

.include "${MASTERDIR}/Makefile"
