# $FreeBSD$

PORTNAME=	Linux-DesktopFiles
PORTVERSION=	0.25
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vidar@karlsen.tech
COMMENT=	Fast parsing of the Linux desktop files

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure
NO_ARCH=	yes

.include <bsd.port.mk>
