# Created by: Gasol Wu <gasol.wu@gmail.com>
# $FreeBSD: head/devel/pear-PHP_Depend/Makefile 517048 2019-11-08 11:39:00Z tobik $

PORTNAME=	PHP_Depend
PORTVERSION=	1.1.2
PORTREVISION=	1
CATEGORIES=	devel pear
MASTER_SITES=	http://dist.karlsen.tech/

MAINTAINER=	vidar@karlsen.tech
COMMENT=	PHP_Depend design quality metrics for PHP packages

LICENSE=	BSD3CLAUSE

USES=		pear php
PEAR_CHANNEL=	pdepend
USE_PHP=	dom tokenizer simplexml

.include <bsd.port.mk>
