# $FreeBSD$

PORTNAME=	File-Rename
PORTVERSION=	1.10
CATEGORIES=	sysutils perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	vidar@karlsen.tech
COMMENT=	Rename multiple files

LICENSE=	ART10

NO_ARCH=	yes
USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
